#ifndef CONFIG_H
#define CONFIG_H

#define PLAYER_COUNT 2
#define LANE_COUNT 3

#define PLAYER_1 0
#define PLAYER_2 1

#define INITIAL_LIFE 3
#define MAX_LIFE 5

#define MAX_OBSTACLES 40
#define ROAD_HEIGHT 14

#define FRAME_DELAY_MS 50

#define OBSTACLE_START_INTERVAL_MS 700
#define OBSTACLE_MIN_INTERVAL_MS 300
#define DIFFICULTY_STEP_MS 10000

#define ITEM_SPAWN_INTERVAL_MS 5000
#define ITEM_SPAWN_CHANCE 45

#define ITEM_MASH_LIMIT 5
#define ITEM_MASH_TIME_MS 2000

#define SCORE_SURVIVE_PER_SEC 10
#define SCORE_AVOID_OBSTACLE 20
#define SCORE_ITEM_SUCCESS 30
#define SCORE_COLLISION_PENALTY 30

#endif